using TecAxle.Hrms.Application.Common;

namespace TecAxle.Hrms.Application.TenantConfiguration.Commands.UpdateTenantSettings;

public record UpdateTenantSettingsCommand(
    // General
    string? FiscalYearStartMonth,
    string? WeekStartDay,
    string? DateFormat,
    string? TimeFormat,
    string? NumberFormat,
    // Attendance
    bool EnableGpsAttendance,
    bool EnableNfcAttendance,
    bool EnableBiometricAttendance,
    bool EnableManualAttendance,
    bool AutoCheckOutEnabled,
    string? AutoCheckOutTime,
    int LateGracePeriodMinutes,
    int EarlyLeaveGracePeriodMinutes,
    bool TrackBreakTime,
    int MinimumWorkingHoursForPresent,
    // Leave
    bool AllowNegativeLeaveBalance,
    bool RequireAttachmentForSickLeave,
    int MinDaysBeforeLeaveRequest,
    bool AllowHalfDayLeave,
    bool AllowLeaveEncashment,
    string? LeaveYearStart,
    // Payroll
    int PayrollCutOffDay,
    string? PayrollCurrency,
    bool EnableEndOfServiceCalc,
    string? SalaryCalculationBasis,
    // Approval
    bool AutoApproveAfterTimeout,
    int DefaultApprovalTimeoutHours,
    bool AllowSelfApproval,
    bool RequireApprovalComments,
    // Notification
    bool EnableEmailNotifications,
    bool EnablePushNotifications,
    bool EnableSmsNotifications,
    bool NotifyManagerOnLeaveRequest,
    bool NotifyEmployeeOnApproval,
    bool DailyAttendanceSummaryEnabled,
    // Mobile
    bool MobileCheckInEnabled,
    bool RequireNfcForMobile,
    bool RequireGpsForMobile,
    bool AllowMockLocation,
    // Security
    int PasswordExpiryDays,
    int MaxLoginAttempts,
    int SessionTimeoutMinutes,
    bool Require2FA,
    int PasswordHistoryCount
) : ICommand<Result>;
