// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TimeAttendanceSystem.Infrastructure.Persistence;

#nullable disable

namespace TimeAttendanceSystem.Infrastructure.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(TimeAttendanceDbContext))]
    [Migration("20251231100000_AddTimeoutActionToWorkflowStep")]
    partial class AddTimeoutActionToWorkflowStep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only adds a single column,
            // the full model is in the ModelSnapshot
        }
    }
}
